#!/bin/bash

# Scaffold script for Next.js + Shared Library Monorepo (Rush.js Starter)
# This script creates the complete project structure from scratch

set -e  # Exit on error

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}🚀 Scaffolding Next.js + Shared Library Monorepo${NC}"
echo ""

# Get the directory where the script is located
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$SCRIPT_DIR"

echo -e "${GREEN}Creating directory structure...${NC}"

# Create main directories
mkdir -p apps/web-app/src/app
mkdir -p libraries/shared-lib/src
mkdir -p common/config/rush
# Note: common/scripts/ will be created by Rush during rush update
mkdir -p common/git-hooks
# Note: common/temp/ will be created by Rush during rush update

echo -e "${GREEN}Creating rush.json...${NC}"
cat > "$PROJECT_ROOT/rush.json" << 'EOF'
/**
 * This is the main configuration file for Rush.
 * For full documentation, please see https://rushjs.io
 */
{
  "$schema": "https://developer.microsoft.com/json-schemas/rush/v5/rush.schema.json",

  "rushVersion": "5.162.0",
  "pnpmVersion": "10.20.0",
  "nodeSupportedVersionRange": ">=22.20.0 <23.0.0",

  "gitPolicy": {},

  "repository": {},

  "eventHooks": {
    "preRushInstall": [],
    "postRushInstall": [],
    "preRushBuild": [],
    "postRushBuild": [],
    "preRushx": [],
    "postRushx": []
  },

  "variants": [],

  "projects": [
    {
      "packageName": "@myorg/web-app",
      "projectFolder": "apps/web-app"
    },
    {
      "packageName": "@myorg/shared-lib",
      "projectFolder": "libraries/shared-lib",
      "shouldPublish": false
    }
  ]
}
EOF

echo -e "${GREEN}Creating web-app package.json...${NC}"
cat > "$PROJECT_ROOT/apps/web-app/package.json" << 'EOF'
{
  "name": "@myorg/web-app",
  "version": "0.1.0",
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "eslint",
    "lint:fix": "eslint --fix"
  },
  "dependencies": {
    "next": "^16.0.1",
    "react": "^19.2.0",
    "react-dom": "^19.2.0",
    "@myorg/shared-lib": "workspace:*"
  },
  "devDependencies": {
    "typescript": "^5.0.0",
    "@types/react": "^18.0.0",
    "@types/node": "^20.0.0"
  }
}
EOF

echo -e "${GREEN}Creating shared-lib package.json...${NC}"
cat > "$PROJECT_ROOT/libraries/shared-lib/package.json" << 'EOF'
{
  "name": "@myorg/shared-lib",
  "version": "0.1.0",
  "main": "dist/index.js",
  "types": "dist/index.d.ts",
  "exports": {
    ".": {
      "types": "./dist/index.d.ts",
      "import": "./src/index.ts",
      "require": "./dist/index.js"
    }
  },
  "scripts": {
    "build": "tsc --build",
    "watch": "tsc --build --watch"
  },
  "peerDependencies": {
    "react": "^18.0.0",
    "react-dom": "^18.0.0"
  },
  "devDependencies": {
    "typescript": "^5.0.0",
    "@types/react": "^18.0.0",
    "@types/react-dom": "^18.0.0"
  }
}
EOF

echo -e "${GREEN}Creating Next.js configuration...${NC}"
cat > "$PROJECT_ROOT/apps/web-app/next.config.ts" << 'EOF'
/** @type {import('next').NextConfig} */
const nextConfig = {
  turbopack: {
    root: "../../", // point 2 levels up to your monorepo root
  },
  transpilePackages: ["@myorg/shared-lib"],
};

module.exports = nextConfig;
EOF

echo -e "${GREEN}Creating web-app tsconfig.json...${NC}"
cat > "$PROJECT_ROOT/apps/web-app/tsconfig.json" << 'EOF'
{
  "compilerOptions": {
    "target": "ES2017",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": false,
    "noEmit": true,
    "incremental": true,
    "module": "esnext",
    "esModuleInterop": true,
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "react-jsx",
    "plugins": [
      {
        "name": "next"
      }
    ]
  },
  "include": [
    "next-env.d.ts",
    ".next/types/**/*.ts",
    ".next/dev/types/**/*.ts",
    "**/*.mts",
    "**/*.ts",
    "**/*.tsx"
  ],
  "exclude": [
    "node_modules"
  ]
}
EOF

echo -e "${GREEN}Creating shared-lib tsconfig.json...${NC}"
cat > "$PROJECT_ROOT/libraries/shared-lib/tsconfig.json" << 'EOF'
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "ESNext",
    "jsx": "react-jsx",
    "declaration": true,
    "declarationMap": true,
    "outDir": "dist",
    "rootDir": "src",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "lib": ["DOM", "ESNext"],
    "moduleResolution": "node"
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "dist"]
}
EOF

# Note: next-env.d.ts will be auto-generated by Next.js when you run next dev or next build

echo -e "${GREEN}Creating shared library source files...${NC}"
cat > "$PROJECT_ROOT/libraries/shared-lib/src/SharedComponent.tsx" << 'EOF'
import React from "react";

export function SharedComponent() {
  return (
    <div style={{ padding: "1rem", backgroundColor: "#eef" }}>
      Hello from SharedComponent!
    </div>
  );
}
EOF

cat > "$PROJECT_ROOT/libraries/shared-lib/src/index.ts" << 'EOF'
export { SharedComponent } from "./SharedComponent";
EOF

echo -e "${GREEN}Creating Next.js app page...${NC}"
cat > "$PROJECT_ROOT/apps/web-app/src/app/page.tsx" << 'EOF'
import { SharedComponent } from "@myorg/shared-lib";

export default function Page() {
  return (
    <div>
      <h1>Hello, Next.js!!</h1>
      <SharedComponent />
    </div>
  );
}
EOF

echo -e "${GREEN}Creating Next.js layout...${NC}"
cat > "$PROJECT_ROOT/apps/web-app/src/app/layout.tsx" << 'EOF'
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Next.js Monorepo App",
  description: "A Next.js application in a Rush.js monorepo",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
EOF

echo -e "${GREEN}Creating basic globals.css...${NC}"
cat > "$PROJECT_ROOT/apps/web-app/src/app/globals.css" << 'EOF'
* {
  box-sizing: border-box;
  padding: 0;
  margin: 0;
}

html,
body {
  max-width: 100vw;
  overflow-x: hidden;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen',
    'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue',
    sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
EOF

echo -e "${GREEN}Creating Rush configuration files...${NC}"

# common-versions.json
cat > "$PROJECT_ROOT/common/config/rush/common-versions.json" << 'EOF'
{
  "$schema": "https://developer.microsoft.com/json-schemas/rush/v5/common-versions.schema.json",
  "preferredVersions": {},
  "allowedAlternativeVersions": {}
}
EOF

# pnpm-config.json
cat > "$PROJECT_ROOT/common/config/rush/pnpm-config.json" << 'EOF'
{
  "$schema": "https://developer.microsoft.com/json-schemas/rush/v5/pnpm-config.schema.json",
  "useWorkspaces": true,
  "pnpmLockfilePolicies": {},
  "globalOverrides": {},
  "globalPeerDependencyRules": {},
  "globalPackageExtensions": {},
  "globalNeverBuiltDependencies": [],
  "globalIgnoredOptionalDependencies": [],
  "globalAllowedDeprecatedVersions": {},
  "globalPatchedDependencies": {},
  "unsupportedPackageJsonSettings": {}
}
EOF

# command-line.json
cat > "$PROJECT_ROOT/common/config/rush/command-line.json" << 'EOF'
{
  "$schema": "https://developer.microsoft.com/json-schemas/rush/v5/command-line.schema.json",
  "commands": [],
  "parameters": []
}
EOF

# rush-plugins.json
cat > "$PROJECT_ROOT/common/config/rush/rush-plugins.json" << 'EOF'
{
  "$schema": "https://developer.microsoft.com/json-schemas/rush/v5/rush-plugins.schema.json",
  "plugins": []
}
EOF

# Create minimal other config files
cat > "$PROJECT_ROOT/common/config/rush/artifactory.json" << 'EOF'
{
  "$schema": "https://developer.microsoft.com/json-schemas/rush/v5/artifactory.schema.json",
  "packageRegistry": {
    "enabled": false,
    "registryUrl": "",
    "userNpmrcLinesToAdd": [],
    "artifactoryWebsiteUrl": "",
    "messageOverrides": {}
  }
}
EOF

cat > "$PROJECT_ROOT/common/config/rush/build-cache.json" << 'EOF'
{
  "$schema": "https://developer.microsoft.com/json-schemas/rush/v5/build-cache.schema.json",
  "buildCacheEnabled": false,
  "cacheProvider": "local-only"
}
EOF

cat > "$PROJECT_ROOT/common/config/rush/cobuild.json" << 'EOF'
{
  "$schema": "https://developer.microsoft.com/json-schemas/rush/v5/cobuild.schema.json",
  "cobuildFeatureEnabled": false,
  "cobuildLockProvider": "redis"
}
EOF

cat > "$PROJECT_ROOT/common/config/rush/custom-tips.json" << 'EOF'
{
  "$schema": "https://developer.microsoft.com/json-schemas/rush/v5/custom-tips.schema.json",
  "customTips": []
}
EOF

cat > "$PROJECT_ROOT/common/config/rush/experiments.json" << 'EOF'
{
  "$schema": "https://developer.microsoft.com/json-schemas/rush/v5/experiments.schema.json"
}
EOF

cat > "$PROJECT_ROOT/common/config/rush/subspaces.json" << 'EOF'
{
  "$schema": "https://developer.microsoft.com/json-schemas/rush/v5/subspaces.schema.json",
  "subspacesEnabled": false,
  "splitWorkspaceCompatibility": false,
  "preventSelectingAllSubspaces": false,
  "subspaceNames": []
}
EOF

cat > "$PROJECT_ROOT/common/config/rush/version-policies.json" << 'EOF'
[]
EOF

echo -e "${GREEN}Creating .npmrc...${NC}"
cat > "$PROJECT_ROOT/common/config/rush/.npmrc" << 'EOF'
# Rush uses this file to configure the NPM package registry during installation.  It is applicable
# to PNPM, NPM, and Yarn package managers.  It is used by operations such as "rush install",
# "rush update", and the "install-run.js" scripts.
#
# NOTE: The "rush publish" command uses .npmrc-publish instead.
#
# Before invoking the package manager, Rush will generate an .npmrc in the folder where installation
# is performed.  This generated file will omit any config lines that reference environment variables
# that are undefined in that session; this avoids problems that would otherwise result due to
# a missing variable being replaced by an empty string.
#
# If "subspacesEnabled" is true in subspaces.json, the generated file will merge settings from
# "common/config/rush/.npmrc" and "common/config/subspaces/<name>/.npmrc", with the latter taking
# precedence.
#
# * * * SECURITY WARNING * * *
#
# It is NOT recommended to store authentication tokens in a text file on a lab machine, because
# other unrelated processes may be able to read that file.  Also, the file may persist indefinitely,
# for example if the machine loses power.  A safer practice is to pass the token via an
# environment variable, which can be referenced from .npmrc using ${} expansion.  For example:
#
#   //registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}
#

# Explicitly specify the NPM registry that "rush install" and "rush update" will use by default:
registry=https://registry.npmjs.org/

# Optionally provide an authentication token for the above registry URL (if it is a private registry):
# //registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}

# Change this to "true" if your registry requires authentication for read-only operations:
always-auth=false
EOF

echo -e "${GREEN}Creating .pnpmfile.cjs...${NC}"
cat > "$PROJECT_ROOT/common/config/rush/.pnpmfile.cjs" << 'EOF'
'use strict';

/**
 * When using the PNPM package manager, you can use pnpmfile.js to workaround
 * dependencies that have mistakes in their package.json file.  (This feature is
 * functionally similar to Yarn's "resolutions".)
 *
 * For details, see the PNPM documentation:
 * https://pnpm.io/pnpmfile#hooks
 *
 * IMPORTANT: SINCE THIS FILE CONTAINS EXECUTABLE CODE, MODIFYING IT IS LIKELY TO INVALIDATE
 * ANY CACHED DEPENDENCY ANALYSIS.  After any modification to pnpmfile.js, it's recommended to run
 * "rush update --full" so that PNPM will recalculate all version selections.
 */
module.exports = {
  hooks: {
    readPackage
  }
};

/**
 * This hook is invoked during installation before a package's dependencies
 * are selected.
 * The `packageJson` parameter is the deserialized package.json
 * contents for the package that is about to be installed.
 * The `context` parameter provides a log() function.
 * The return value is the updated object.
 */
function readPackage(packageJson, context) {

  // // The karma types have a missing dependency on typings from the log4js package.
  // if (packageJson.name === '@types/karma') {
  //  context.log('Fixed up dependencies for @types/karma');
  //  packageJson.dependencies['log4js'] = '0.6.38';
  // }

  return packageJson;
}
EOF

echo -e "${GREEN}Creating .gitignore...${NC}"
cat > "$PROJECT_ROOT/.gitignore" << 'EOF'
# Dependencies
node_modules/
.pnp
.pnp.js

# Testing
coverage/

# Next.js
.next/
out/
build/
dist/

# Production
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*
lerna-debug.log*

# Misc
.DS_Store
*.pem

# Debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Local env files
.env*.local
.env

# Vercel
.vercel

# TypeScript
*.tsbuildinfo
next-env.d.ts

# Rush
common/temp/
common/autoinstallers/*/node_modules/
common/autoinstallers/*/.pnpm-store/
rush-logs/
*.lock

# IDE
.vscode/
.idea/
*.swp
*.swo
*~

# OS
.DS_Store
Thumbs.db
EOF

echo ""
echo -e "${GREEN}✅ Project structure created successfully!${NC}"
echo ""

# Check if Rush is installed
if command -v rush &> /dev/null; then
    echo -e "${GREEN}Rush.js detected! Running rush update to generate scripts and install dependencies...${NC}"
    echo ""
    
    # Run rush update to generate scripts and install dependencies
    # This will create:
    # - common/scripts/install-run-rush.js and related scripts
    # - common/temp/pnpm-workspace.yaml
    # - Install all dependencies
    # - Link local packages
    
    cd "$PROJECT_ROOT"
    rush update || {
        echo ""
        echo -e "${YELLOW}⚠️  rush update encountered an error. This might be expected if Rush needs to be installed first.${NC}"
        echo ""
    }
else
    echo -e "${YELLOW}⚠️  Rush.js not found. Skipping automatic setup.${NC}"
    echo ""
fi

echo -e "${YELLOW}📋 Next Steps:${NC}"
echo ""
if ! command -v rush &> /dev/null; then
    echo "1. Install Rush.js:"
    echo "   npm install -g @microsoft/rush"
    echo ""
fi
echo "2. Initialize Rush in the project (if not already done):"
echo "   cd $PROJECT_ROOT"
echo "   rush update"
echo ""
echo "   This command will:"
echo "   - Generate Rush installation scripts in common/scripts/"
echo "   - Create pnpm-workspace.yaml in common/temp/"
echo "   - Install all dependencies"
echo "   - Link local packages together"
echo ""
echo "3. Build the projects:"
echo "   rush build"
echo ""
echo "4. Start development:"
echo "   cd apps/web-app"
echo "   rushx dev"
echo ""
echo -e "${BLUE}📖 For more information, see README.md${NC}"
echo ""
echo -e "${GREEN}Note:${NC} The following files are auto-generated and should not be manually created:"
echo "  - common/scripts/* (generated by Rush)"
echo "  - common/temp/pnpm-workspace.yaml (generated by Rush)"
echo "  - apps/web-app/next-env.d.ts (generated by Next.js)"
echo ""
